/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as ProcessoRouteImport } from './routes/processo'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'
import { Route as ProjetosSlugRouteImport } from './routes/projetos.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessoRoute = ProcessoRouteImport.update({
  id: '/processo',
  path: '/processo',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicosRoute,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjetosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/faq': typeof FaqRoute
  '/orcamento': typeof OrcamentoRoute
  '/processo': typeof ProcessoRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/servicos': typeof ServicosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/faq': typeof FaqRoute
  '/orcamento': typeof OrcamentoRoute
  '/processo': typeof ProcessoRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/servicos': typeof ServicosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/faq': typeof FaqRoute
  '/orcamento': typeof OrcamentoRoute
  '/processo': typeof ProcessoRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/servicos': typeof ServicosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contactos'
    | '/faq'
    | '/orcamento'
    | '/processo'
    | '/projetos'
    | '/servicos'
    | '/sobre'
    | '/projetos/$slug'
    | '/servicos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contactos'
    | '/faq'
    | '/orcamento'
    | '/processo'
    | '/projetos'
    | '/servicos'
    | '/sobre'
    | '/projetos/$slug'
    | '/servicos/$slug'
  id:
    | '__root__'
    | '/'
    | '/contactos'
    | '/faq'
    | '/orcamento'
    | '/processo'
    | '/projetos'
    | '/servicos'
    | '/sobre'
    | '/projetos/$slug'
    | '/servicos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactosRoute: typeof ContactosRoute
  FaqRoute: typeof FaqRoute
  OrcamentoRoute: typeof OrcamentoRoute
  ProcessoRoute: typeof ProcessoRoute
  ProjetosRoute: typeof ProjetosRouteWithChildren
  ServicosRoute: typeof ServicosRouteWithChildren
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processo': {
      id: '/processo'
      path: '/processo'
      fullPath: '/processo'
      preLoaderRoute: typeof ProcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/projetos/$slug': {
      id: '/projetos/$slug'
      path: '/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof ProjetosRoute
    }
  }
}

interface ProjetosRouteChildren {
  ProjetosSlugRoute: typeof ProjetosSlugRoute
}

const ProjetosRouteChildren: ProjetosRouteChildren = {
  ProjetosSlugRoute: ProjetosSlugRoute,
}

const ProjetosRouteWithChildren = ProjetosRoute._addFileChildren(
  ProjetosRouteChildren,
)

interface ServicosRouteChildren {
  ServicosSlugRoute: typeof ServicosSlugRoute
}

const ServicosRouteChildren: ServicosRouteChildren = {
  ServicosSlugRoute: ServicosSlugRoute,
}

const ServicosRouteWithChildren = ServicosRoute._addFileChildren(
  ServicosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactosRoute: ContactosRoute,
  FaqRoute: FaqRoute,
  OrcamentoRoute: OrcamentoRoute,
  ProcessoRoute: ProcessoRoute,
  ProjetosRoute: ProjetosRouteWithChildren,
  ServicosRoute: ServicosRouteWithChildren,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
